### ISSUE TITLE
fv3config.run_docker swallows error messages 

### ISSUE THREAD

**Issue by nbren12** [VulcanClimateModeling/fv3config#58]
Currently, fv3config swallows error messages that occur before the FV3 model is run. In addition, it automatically deletes the container making it impossible to inspect after the fact. This makes it difficult/impossible to debug errors in `fv3config.run_native` that can arise from errors in the config object or the `fv3config.run_native`.

**Comment by nbren12** [comment]
Actually it does output errors, but just sends it to the command line stdout (which doesn't appear in a jupyter notebook for some reason). It shows up on the terminal running the jupyter notebook server.

**Comment by mcgibbon** [comment]
I thought the default behavior was to write to out and err files?

**Comment by nbren12** [comment]
IIRC the errors that happen before/after that (e.g. during `write_run_directory) will be outputted to the actual STDOUT.

**Comment by mcgibbon** [comment]
I'm a little confused as to how fv3config can "swallow" its own stack traces? What is it expected to do other than send to stdout, and rely on whatever you're using to properly display stdout?

**Comment by nbren12** [comment]
I can't remember what the exact issue is. I think the output stderr.log and stdout.log files won't be available under certain circumstances. Also the `--rm` flag makes it difficult to debug the container. Usually it would be possible to run the container and inspect its logs and contents for debugging purposes.

**Comment by mcgibbon** [comment]
It sounds like in `run_docker` we want to call `docker run` in a way that it will store its stdout and stderr somewhere we can retrieve it.

**Comment by nbren12** [comment]
`docker run` will do that automatically if you print to the terminal. Then these logs can be retrieved with `docker logs`.

**Comment by nbren12** [comment]
GKE likewise has a mechanism for catching catching logging information from K8s jobs.

**Comment by mcgibbon** [comment]
OK, so what's stopping the logs from being retrieved with `docker logs`?

**Comment by nbren12** [comment]
the fact that they are being piped to `stderr.log` and `stdout.log`.

**Comment by mcgibbon** [comment]
Here you seem to say the problem is that errors should not be printed to stdout:
> Actually it does output errors, but just sends it to the command line stdout (which doesn't appear in a jupyter notebook for some reason). It shows up on the terminal running the jupyter notebook server.
And that you can't retrieve errors printed to stdout:
> IIRC the errors that happen before/after that (e.g. during `write_run_directory) will be outputted to the actual STDOUT.

But now you're saying the problem is that you can't retrieve errors piped to log files, and instead want them piped to stdout? I must not be understanding.

Could you write down a MCVE comparing actual and expected behavior to help me understand the issue?

On a side note, stdout.log and stderr.log should be viewable in the outdir if `python3 -m fv3gfs.run` crashes. You only won't be able to retrieve those files if `fv3config.fv3run` crashes, in which case the crash should be reported in console as there's no piping of `fv3config.fv3run` output to stdout or stderr. In short,

fv3config.fv3run (baremetal) -> fv3config.fv3run (inside docker) -> fv3gfs.run

Only the last step has its log files piped to disk. The second step should copy the outdir even if the last step crashes. If the second step crashes, it should output to stdout and stderr. The `subprocess.check_call` command in the first step does no output redirection. If you're running on kubernetes, you just have the last two steps.

**Comment by nbren12** [comment]
I think I mostly agree with you. You're the one driving this conversation, Jeremy. Feel free to close this issue, since as I said above, it mostly was an issue with running via the jupyter notebook. In that case, one of the subprocess-docker-subprocess layers was not printed to output cell, but rather printed in the terminal console running notebook server, which was confusing.

If I were to change anything, I would add an option to [run_native](https://github.com/VulcanClimateModeling/fv3config/blob/1ab3f089f022b6d3954e8d199f12d469996f56a4/fv3config/fv3run/_native.py#L132) to avoid piping the output to those files. This approach short-circuits the dockers' and k8s's mechanisms for capturing and interacting with stderr and stdout. For instance, one would like to use `kubectl logs <podname>` to print the outputs of a running job.

**Comment by mcgibbon** [comment]
Haha ok great. I just felt weird having an issue open with no plan or route for anybody to fix it.

We talked at one point about adding optional out and err arguments to run_native which would pipe to a location you choose (only accessible from within python, not the command line). Feel free to open a new issue with that, if you like.
